### ISSUE TITLE
app.js, findFormEl

### ISSUE THREAD

**Issue by Eeenkeeei** [Eeenkeeei/Read-Later#1]
Попытка сделать обновление поиска при введении символов, а не при нажатии на кнопку. 
1) Как можно отменить перезагрузку страницы, если в type у addEventListener стоит input? 
2) Как можно обойтись без замены события у формы с submit на input. Я пробовал повесить change на само поле, на значение поля, ничего не срабатывало. Если повесить на форму input - работает, но не нравится перезагрузка страницы. 
3) После первой загрузки страницы вводим символы. Поиск работает после ввода первого символа. Стираем все символы, как дать браузеру понять, что стерлись все символы, и как после этого стирать оставшийся результат после предыдущего ввода?
4) После того как один раз ввели-стерли все символы, поиск начинает работать только после ввода второго символа. На ввод первого символа реакции нет, после второго ищет как и в начале. Почему?
https://github.com/Eeenkeeei/Read-Later/blob/6e865741143adcf919a52579c5df904e71cc4fa4/src/js/app.js#L57-L87

**Comment by coursar** [comment]
1. Перезагрузка происходит из-за клавиши Enter, вы можете отменить у формы событие 'submit'.
1. См. предыдущий пункт
1. Отслеживаете сами value - если пустое, тогда вычищаете список найденного
1. Задебажьте - увидите, что после ввода первого символа `validationFindForm` работает не правильно и вы выходите из обработчика на 65 строке
