### ISSUE TITLE
storage.js, функция finder

### ISSUE THREAD

**Issue by Eeenkeeei** [Eeenkeeei/Read-Later#2]
1) Написанная функция ищет ЛЮБОЕ совпадение с имеющимися записями. Если есть название записи "Youtube", а я впишу в поиск "u", то покажется результат. То же самое с тегами. Если есть тег "#video" и в поиск ввести "#o", покажется то же самое. Это нормальное поведение или нам нужно искать именно точное совпадение?
https://github.com/Eeenkeeei/Read-Later/blob/6e865741143adcf919a52579c5df904e71cc4fa4/src/js/storage.js#L50-L108

2) Если есть 2 одинаковых названия в списке, то если вбить в поиск название одного из них, будет 4 результата с одинаковыми названиями, теги и ссылки могут быть разные. Я нашел ошибку здесь, но не могу понять как исправить 
https://github.com/Eeenkeeei/Read-Later/blob/6e865741143adcf919a52579c5df904e71cc4fa4/src/js/storage.js#L71-L80

**Comment by coursar** [comment]
1. Зависит от вашей логики - по-хорошему, в самом простом варианте, лучше начинать искать после 3-4 символов
1. Можете прочитать про спец.класс `Set()` - он убирает дубликаты, а можно просто отфильтровать всё на наличие дублей:

```javascript
const unique = this.resultObjects.filter((item, index, arr) => {
    return arr.indexOf(item) === index;
});
```
